package com.danielvilha.barbershop.features.util

import android.content.Context
import android.telephony.TelephonyManager
import android.util.Log
import java.util.Locale

data class CountryCode(
    val name: String,
    val code: String,
    val flag: String
)

data class RawCountry(
    val code: String,
    val phone: String,
    val name: String
) {
    companion object {
        fun getFlagEmoji(countryCode: String): String {
            return countryCode.uppercase().map { char ->
                Character.toChars(0x1F1E6 - 'A'.code + char.code)
            }.joinToString("") { String(it) }
        }

        fun getDeviceCountryIso(context: Context): String {
            try {
                val telephonyManager = context.getSystemService(Context.TELEPHONY_SERVICE) as? TelephonyManager
                val networkCountryIso = telephonyManager?.networkCountryIso
                if (!networkCountryIso.isNullOrBlank()) {
                    return networkCountryIso
                }

                return Locale.getDefault().country
            } catch (e: Exception) {
                Log.e("CountryCode", "getDeviceCountryIso: ", e.cause)
                return Locale.getDefault().country
            }
        }

        fun getCountries(): List<CountryCode> {
            val rawCountries = listOf(
                RawCountry("ad", "376", "Andorra"),
                RawCountry("ae", "971", "United Arab Emirates (UAE)"),
                RawCountry("af", "93", "Afghanistan"),
                RawCountry("ag", "1", "Antigua and Barbuda"),
                RawCountry("ai", "1", "Anguilla"),
                RawCountry("al", "355", "Albania"),
                RawCountry("am", "374", "Armenia"),
                RawCountry("ao", "244", "Angola"),
                RawCountry("aq", "672", "Antarctica"),
                RawCountry("ar", "54", "Argentina"),
                RawCountry("as", "1", "American Samoa"),
                RawCountry("at", "43", "Austria"),
                RawCountry("au", "61", "Australia"),
                RawCountry("aw", "297", "Aruba"),
                RawCountry("ax", "358", "Åland Islands"),
                RawCountry("az", "994", "Azerbaijan"),
                RawCountry("ba", "387", "Bosnia And Herzegovina"),
                RawCountry("bb", "1", "Barbados"),
                RawCountry("bd", "880", "Bangladesh"),
                RawCountry("be", "32", "Belgium"),
                RawCountry("bf", "226", "Burkina Faso"),
                RawCountry("bg", "359", "Bulgaria"),
                RawCountry("bh", "973", "Bahrain"),
                RawCountry("bi", "257", "Burundi"),
                RawCountry("bj", "229", "Benin"),
                RawCountry("bl", "590", "Saint Barthélemy"),
                RawCountry("bm", "1", "Bermuda"),
                RawCountry("bn", "673", "Brunei Darussalam"),
                RawCountry("bo", "591", "Bolivia, Plurinational State Of"),
                RawCountry("br", "55", "Brazil"),
                RawCountry("bs", "1", "Bahamas"),
                RawCountry("bt", "975", "Bhutan"),
                RawCountry("bw", "267", "Botswana"),
                RawCountry("by", "375", "Belarus"),
                RawCountry("bz", "501", "Belize"),
                RawCountry("ca", "1", "Canada"),
                RawCountry("cc", "61", "Cocos (keeling) Islands"),
                RawCountry("cd", "243", "Congo, The Democratic Republic Of The"),
                RawCountry("cf", "236", "Central African Republic"),
                RawCountry("cg", "242", "Congo"),
                RawCountry("ch", "41", "Switzerland"),
                RawCountry("ci", "225", "Côte D'ivoire"),
                RawCountry("ck", "682", "Cook Islands"),
                RawCountry("cl", "56", "Chile"),
                RawCountry("cm", "237", "Cameroon"),
                RawCountry("cn", "86", "China"),
                RawCountry("co", "57", "Colombia"),
                RawCountry("cr", "506", "Costa Rica"),
                RawCountry("cu", "53", "Cuba"),
                RawCountry("cv", "238", "Cape Verde"),
                RawCountry("cw", "599", "Curaçao"),
                RawCountry("cx", "61", "Christmas Island"),
                RawCountry("cy", "357", "Cyprus"),
                RawCountry("cz", "420", "Czech Republic"),
                RawCountry("de", "49", "Germany"),
                RawCountry("dj", "253", "Djibouti"),
                RawCountry("dk", "45", "Denmark"),
                RawCountry("dm", "1", "Dominica"),
                RawCountry("do", "1", "Dominican Republic"),
                RawCountry("dz", "213", "Algeria"),
                RawCountry("ec", "593", "Ecuador"),
                RawCountry("ee", "372", "Estonia"),
                RawCountry("eg", "20", "Egypt"),
                RawCountry("er", "291", "Eritrea"),
                RawCountry("es", "34", "Spain"),
                RawCountry("et", "251", "Ethiopia"),
                RawCountry("fi", "358", "Finland"),
                RawCountry("fj", "679", "Fiji"),
                RawCountry("fk", "500", "Falkland Islands (malvinas)"),
                RawCountry("fm", "691", "Micronesia, Federated States Of"),
                RawCountry("fo", "298", "Faroe Islands"),
                RawCountry("fr", "33", "France"),
                RawCountry("ga", "241", "Gabon"),
                RawCountry("gb", "44", "United Kingdom"),
                RawCountry("gd", "1", "Grenada"),
                RawCountry("ge", "995", "Georgia"),
                RawCountry("gf", "594", "French Guyana"),
                RawCountry("gh", "233", "Ghana"),
                RawCountry("gi", "350", "Gibraltar"),
                RawCountry("gl", "299", "Greenland"),
                RawCountry("gm", "220", "Gambia"),
                RawCountry("gn", "224", "Guinea"),
                RawCountry("gp", "450", "Guadeloupe"),
                RawCountry("gq", "240", "Equatorial Guinea"),
                RawCountry("gr", "30", "Greece"),
                RawCountry("gt", "502", "Guatemala"),
                RawCountry("gu", "1", "Guam"),
                RawCountry("gw", "245", "Guinea-bissau"),
                RawCountry("gy", "592", "Guyana"),
                RawCountry("hk", "852", "Hong Kong"),
                RawCountry("hn", "504", "Honduras"),
                RawCountry("hr", "385", "Croatia"),
                RawCountry("ht", "509", "Haiti"),
                RawCountry("hu", "36", "Hungary"),
                RawCountry("id", "62", "Indonesia"),
                RawCountry("ie", "353", "Ireland"),
                RawCountry("il", "972", "Israel"),
                RawCountry("im", "44", "Isle Of Man"),
                RawCountry("is", "354", "Iceland"),
                RawCountry("in", "91", "India"),
                RawCountry("io", "246", "British Indian Ocean Territory"),
                RawCountry("iq", "964", "Iraq"),
                RawCountry("ir", "98", "Iran, Islamic Republic Of"),
                RawCountry("it", "39", "Italy"),
                RawCountry("je", "44", "Jersey"),
                RawCountry("jm", "1", "Jamaica"),
                RawCountry("jo", "962", "Jordan"),
                RawCountry("jp", "81", "Japan"),
                RawCountry("ke", "254", "Kenya"),
                RawCountry("kg", "996", "Kyrgyzstan"),
                RawCountry("kh", "855", "Cambodia"),
                RawCountry("ki", "686", "Kiribati"),
                RawCountry("km", "269", "Comoros"),
                RawCountry("kn", "1", "Saint Kitts and Nevis"),
                RawCountry("kp", "850", "North Korea"),
                RawCountry("kr", "82", "South Korea"),
                RawCountry("kw", "965", "Kuwait"),
                RawCountry("ky", "1", "Cayman Islands"),
                RawCountry("kz", "7", "Kazakhstan"),
                RawCountry("la", "856", "Lao People's Democratic Republic"),
                RawCountry("lb", "961", "Lebanon"),
                RawCountry("lc", "1", "Saint Lucia"),
                RawCountry("li", "423", "Liechtenstein"),
                RawCountry("lk", "94", "Sri Lanka"),
                RawCountry("lr", "231", "Liberia"),
                RawCountry("ls", "266", "Lesotho"),
                RawCountry("lt", "370", "Lithuania"),
                RawCountry("lu", "352", "Luxembourg"),
                RawCountry("lv", "371", "Latvia"),
                RawCountry("ly", "218", "Libya"),
                RawCountry("ma", "212", "Morocco"),
                RawCountry("mc", "377", "Monaco"),
                RawCountry("md", "373", "Moldova, Republic Of"),
                RawCountry("me", "382", "Montenegro"),
                RawCountry("mf", "590", "Saint Martin"),
                RawCountry("mg", "261", "Madagascar"),
                RawCountry("mh", "692", "Marshall Islands"),
                RawCountry("mk", "389", "Macedonia (FYROM)"),
                RawCountry("ml", "223", "Mali"),
                RawCountry("mm", "95", "Myanmar"),
                RawCountry("mn", "976", "Mongolia"),
                RawCountry("mo", "853", "Macau"),
                RawCountry("mp", "1", "Northern Mariana Islands"),
                RawCountry("mq", "596", "Martinique"),
                RawCountry("mr", "222", "Mauritania"),
                RawCountry("ms", "1", "Montserrat"),
                RawCountry("mt", "356", "Malta"),
                RawCountry("mu", "230", "Mauritius"),
                RawCountry("mv", "960", "Maldives"),
                RawCountry("mw", "265", "Malawi"),
                RawCountry("mx", "52", "Mexico"),
                RawCountry("my", "60", "Malaysia"),
                RawCountry("mz", "258", "Mozambique"),
                RawCountry("na", "264", "Namibia"),
                RawCountry("nc", "687", "New Caledonia"),
                RawCountry("ne", "227", "Niger"),
                RawCountry("nf", "672", "Norfolk Islands"),
                RawCountry("ng", "234", "Nigeria"),
                RawCountry("ni", "505", "Nicaragua"),
                RawCountry("nl", "31", "Netherlands"),
                RawCountry("no", "47", "Norway"),
                RawCountry("np", "977", "Nepal"),
                RawCountry("nr", "674", "Nauru"),
                RawCountry("nu", "683", "Niue"),
                RawCountry("nz", "64", "New Zealand"),
                RawCountry("om", "968", "Oman"),
                RawCountry("pa", "507", "Panama"),
                RawCountry("pe", "51", "Peru"),
                RawCountry("pf", "689", "French Polynesia"),
                RawCountry("pg", "675", "Papua New Guinea"),
                RawCountry("ph", "63", "Philippines"),
                RawCountry("pk", "92", "Pakistan"),
                RawCountry("pl", "48", "Poland"),
                RawCountry("pm", "508", "Saint Pierre And Miquelon"),
                RawCountry("pn", "870", "Pitcairn Islands"),
                RawCountry("pr", "1", "Puerto Rico"),
                RawCountry("ps", "970", "Palestine"),
                RawCountry("pt", "351", "Portugal"),
                RawCountry("pw", "680", "Palau"),
                RawCountry("py", "595", "Paraguay"),
                RawCountry("qa", "974", "Qatar"),
                RawCountry("re", "262", "Réunion"),
                RawCountry("ro", "40", "Romania"),
                RawCountry("rs", "381", "Serbia"),
                RawCountry("ru", "7", "Russian Federation"),
                RawCountry("rw", "250", "Rwanda"),
                RawCountry("sa", "966", "Saudi Arabia"),
                RawCountry("sb", "677", "Solomon Islands"),
                RawCountry("sc", "248", "Seychelles"),
                RawCountry("sd", "249", "Sudan"),
                RawCountry("se", "46", "Sweden"),
                RawCountry("sg", "65", "Singapore"),
                RawCountry("sh", "290", "Saint Helena, Ascension And Tristan Da Cunha"),
                RawCountry("si", "386", "Slovenia"),
                RawCountry("sk", "421", "Slovakia"),
                RawCountry("sl", "232", "Sierra Leone"),
                RawCountry("sm", "378", "San Marino"),
                RawCountry("sn", "221", "Senegal"),
                RawCountry("so", "252", "Somalia"),
                RawCountry("sr", "597", "Suriname"),
                RawCountry("ss", "211", "South Sudan"),
                RawCountry("st", "239", "Sao Tome And Principe"),
                RawCountry("sv", "503", "El Salvador"),
                RawCountry("sx", "1", "Sint Maarten"),
                RawCountry("sy", "963", "Syrian Arab Republic"),
                RawCountry("sz", "268", "Swaziland"),
                RawCountry("tc", "1", "Turks and Caicos Islands"),
                RawCountry("td", "235", "Chad"),
                RawCountry("tg", "228", "Togo"),
                RawCountry("th", "66", "Thailand"),
                RawCountry("tj", "992", "Tajikistan"),
                RawCountry("tk", "690", "Tokelau"),
                RawCountry("tl", "670", "Timor-leste"),
                RawCountry("tm", "993", "Turkmenistan"),
                RawCountry("tn", "216", "Tunisia"),
                RawCountry("to", "676", "Tonga"),
                RawCountry("tr", "90", "Turkey"),
                RawCountry("tt", "1", "Trinidad & Tobago"),
                RawCountry("tv", "688", "Tuvalu"),
                RawCountry("tw", "886", "Taiwan"),
                RawCountry("tz", "255", "Tanzania, United Republic Of"),
                RawCountry("ua", "380", "Ukraine"),
                RawCountry("ug", "256", "Uganda"),
                RawCountry("us", "1", "United States"),
                RawCountry("uy", "598", "Uruguay"),
                RawCountry("uz", "998", "Uzbekistan"),
                RawCountry("va", "379", "Holy See (vatican City State)"),
                RawCountry("vc", "1", "Saint Vincent & The Grenadines"),
                RawCountry("ve", "58", "Venezuela, Bolivarian Republic Of"),
                RawCountry("vg", "1", "British Virgin Islands"),
                RawCountry("vi", "1", "US Virgin Islands"),
                RawCountry("vn", "84", "Vietnam"),
                RawCountry("vu", "678", "Vanuatu"),
                RawCountry("wf", "681", "Wallis And Futuna"),
                RawCountry("ws", "685", "Samoa"),
                RawCountry("xk", "383", "Kosovo"),
                RawCountry("ye", "967", "Yemen"),
                RawCountry("yt", "262", "Mayotte"),
                RawCountry("za", "27", "South Africa"),
                RawCountry("zm", "260", "Zambia"),
                RawCountry("zw", "263", "Zimbabwe")
            )

            return rawCountries.map {
                CountryCode(
                    name = it.name,
                    code = "+${it.phone}",
                    flag = getFlagEmoji(it.code)
                )
            }
        }
    }
}